import React from 'react'

// Metadata is serializable and safe to pass from Server Components
export const gameMetadata = [
  { id: 1, title: 'Vastu Chitra Interactive' },
  { id: 2, title: 'What Defines a Game?' },
  { id: 3, title: 'Video Game Industry' },
  { id: 4, title: 'Team Structure' },
  { id: 5, title: 'Game Dev Pipeline' },
  { id: 6, title: 'Designer vs Developer' },
  { id: 7, title: 'Behind the Scenes' },
  { id: 8, title: 'Types of Games' },
  { id: 9, title: 'See It In Action' },
  { id: 10, title: '2D vs 2.5D Side-Scrollers' },
  { id: 11, title: 'Small Teams, Big Impact' },
  { id: 12, title: 'Production Scale' },
  { id: 13, title: 'Architecture in Games' },
  { id: 14, title: 'AC Unity & Notre-Dame' },
  { id: 15, title: 'Indian Games Leading the Way' },
  { id: 16, title: 'Studios to Watch' },
  { id: 17, title: 'Case Study: Uncharted' },
  { id: 18, title: 'Events & Government Support' },
  { id: 20, title: 'Publishing Platforms' },
  { id: 21, title: 'Where Indian Studios Publish' },
  { id: 22, title: 'Global Gaming Industry' },
  { id: 23, title: 'Indian Gaming Market' },
  { id: 24, title: 'Ethical Gaming Rules' },
]

// Components are functions and should ONLY be used in Client Components
export const gameComponents = [
  React.lazy(() => import('./Slide01_Cover')),
  React.lazy(() => import('./Slide02_WhatDefinesAGame')),
  React.lazy(() => import('./Slide03_VideoGameIndustry')),
  React.lazy(() => import('./Slide04_TeamStructure')),
  React.lazy(() => import('./Slide05_Pipeline')),
  React.lazy(() => import('./Slide06_DesignerVsDeveloper')),
  React.lazy(() => import('./Slide07_BehindScenes')),
  React.lazy(() => import('./Slide08_TypesOfGames')),
  React.lazy(() => import('./Slide09_SeeItInAction')),
  React.lazy(() => import('./Slide10_SideScroller')),
  React.lazy(() => import('./Slide11_SmallTeams')),
  React.lazy(() => import('./Slide12_SuccessfulStories')),
  React.lazy(() => import('./Slide13_Architecture')),
  React.lazy(() => import('./Slide14_ACUnity')),
  React.lazy(() => import('./Slide15_IndianGames')),
  React.lazy(() => import('./Slide16_OngoingStudio')),
  React.lazy(() => import('./Slide17_Uncharted')),
  React.lazy(() => import('./Slide18_Events')),
  React.lazy(() => import('./Slide20_Platforms')),
  React.lazy(() => import('./Slide21_IndianPublishing')),
  React.lazy(() => import('./Slide22_GlobalIndustry')),
  React.lazy(() => import('./Slide23_IndianMarket')),
  React.lazy(() => import('./Slide24_EthicalGaming')),
]
